### ISSUE TITLE
FilePath cop conflicts with new base RuboCop's Rails/FilePath cop

### ISSUE THREAD

**Issue by mvz** [backus/rubocop-rspec#301] opened 2017-01-17 21:25 UTC
I have configuration for `RSpec/FilePath` in my `.rubocop.yml` file, and RuboCop 0.47.0 complains about it:

```
[..]/reek/.rubocop.yml: RSpec/FilePath has the wrong namespace - should be Rails
```

Also, this causes `RSpec/FilePath` not to be configured 🙁.

**Comment by backus** [comment] 2017-01-17 21:33
Yeah I thought I fixed this in rubocop before they released this new cop but unfortunately I neglected to help them fix their config loading. This is a dupe of #299 which I fixed with https://github.com/bbatsov/rubocop/pull/3914. If you want to request a patch release of rubocop proper to fix this I would support that :wink:

**Comment by backus** [comment] 2017-01-17 21:34
Oh and the workaround should be to depend on RuboCop master. Can you actually confirm for me that this fixes your problem?

**Closed** 2017-01-17 21:33 UTC

**Comment by mvz** [comment] 2017-01-17 22:03
Yes, that fixes my problem, thanks!
