### ISSUE TITLE
False positives in RepeatedExamples

### ISSUE THREAD

**Issue by Darhazer** [backus/rubocop-rspec#321] opened 2017-02-11 10:28 UTC
When a shared examples are used to setup some context, it's possible to have the same examples in different context. For example, this is how we test `Pundit` permissions:

```
it_behaves_like 'admin' do
  it { expect(subject).to permit(user, record) }
end

it_behaves_like 'poweruser' do
  it { expect(subject).to permit(user, record) }
end
```

Is this way of setting tests wrong, or should RepeatedExamples ignore examples in different it_behaves_like blocks?

**Comment by backus** [comment] 2017-02-11 11:02
That should be totally fine. We should probably also check for `(block (send ....) ...)` that [matches the `Includes` language](https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/rspec/language.rb#L64-L73). Adding that to the [`ExampleGroup`](https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/rspec/example_group.rb) would probably help fix this bug.

Thanks for reporting!

**Comment by Kukunin** [comment] 2017-02-16 15:08
got false positive with `rspec-its`:

```ruby
        its([:ssn]) { is_expected.to be_nil }
        its([:current_address]) { is_expected.to be_nil }
```

**Comment by backus** [comment] 2017-02-16 17:19
@kukunin I believe we have a fix in master for that if you want to try it out to confirm

**Comment by Kukunin** [comment] 2017-02-17 09:44
Confirmed. latest release fixed my problem. I don't know about problem of topicstarter. 

Thanks for quick fix

**Comment by yuriidanyliak** [comment] 2017-02-17 09:44
@Kukunin you can also use 

``` ruby
its([:ssn], [:current_address]) { is_expected.to be_nil }
```

**Comment by lauramosher** [comment] 2017-02-23 17:50
A more thorough audit of policies may be necessary. A very scrubbed policy test we have:
```ruby
require "rails_helper"

RSpec.describe RequestPolicy do
  subject(:policy) { described_class }

  permissions :update? do
    it "denies access to update completed requests" do
      request = create(:request, :approved)

      expect(policy).not_to permit(request.user, request)
    end

    it "denies access to update another user's pending requests" do
      request = create(:request, :pending)

      expect(policy).not_to permit(User.new, request)
    end

    it "grants access to update pending requests" do
      request = create(:request, :pending)

      expect(policy).to permit(request.user, request)
    end
  end
end
```

All three of them give me the `Don't repeat examples within an example group.` but they are all different contexts and so should be "repeated."

**Comment by backus** [comment] 2017-02-23 19:56
@lauramosher in that case the issue is that `rubocop-rspec` doesn't know that `permissions` defines a new example group. I need to introduce some sort of configuration that works across rubocop-rspec cops that lets users specify custom example group class methods

**Comment by lauramosher** [comment] 2017-02-24 00:47
That makes sense. Let me know if I can help at all. I'm not wholly familiar with everything that goes into cops, but happy to help if I can.

**Comment by backus** [comment] 2017-02-26 04:01
Thanks @lauramosher! I think a proper solution requires some more complex changes that I would need to figure out. If you are interested in contributing though checkout [issues with the `cop` label](https://github.com/backus/rubocop-rspec/issues?q=is%3Aissue+is%3Aopen+label%3Acop). They are surprisingly easy and fun to work on!

**Comment by backus** [comment] 2017-02-26 22:18
Since the original issue here is fixed thanks to @redross I'm going to close this issue and open up a separate issue for the problem that @lauramosher described

**Closed by backus** 2017-02-26 22:18 UTC
Labels: bug
