### ISSUE TITLE
Cop idea: Enforce stub_const so that dummy classes do not leak across tests

### ISSUE THREAD

**Issue by alexgerstein** [backus/rubocop-rspec#380] opened 2017-03-23 19:06 UTC
Bad
===
```ruby
RSpec.describe 'define some module' do
  class SomeSacrificialClassForTesting
  end

  it 'knows about the sacrificial class' do
    expect(defined?(SomeSacrificialClassForTesting)).to_not be_nil # PASSES
  end
end

RSpec.describe 'a different example group' do
  it 'does not know about the sacrificial class' do
    expect(defined?(SomeSacrificialClassForTesting)).to be_nil # FAILS
  end
end
```

Good
====
```ruby
RSpec.describe 'define some module' do
  before do
    stub_const('SomeSacrificialClassForTesting', Class.new)
  end

  it 'knows about the sacrificial class' do
    expect(defined?(SomeSacrificialClassForTesting)).to_not be_nil # PASSES
  end
end

RSpec.describe 'a different example group' do
  it 'does not know about the sacrificial class' do
    expect(defined?(SomeSacrificialClassForTesting)).to be_nil # PASSES
  end
end
```

**Comment by dgollahon** [comment] 2017-03-23 19:28
This is definitely a good idea, but it appears to be a duplicate of: https://github.com/backus/rubocop-rspec/issues/197 (let me know if you disagree).

I'll close this issue in favor of the original for now. Thanks for the suggestion!

**Closed by dgollahon** 2017-03-23 19:28 UTC

**Comment by alexgerstein** [comment] 2017-03-23 19:52
Ah. I tried searching for an existing issue, but couldn't find one. That one seems to cover it! Thanks, @dgollahon.
